language: node_js

node_js:
  - "12"

branches:
  only:
    - main

install:
  - yarn install --frozen-lockfile --non-interactive

script:
  - yarn test
  - yarn coverage
  # Upload to coveralls, but don't _fail_ if coveralls is down.
  - cat coverage/lcov.info | node_modules/.bin/coveralls || echo "Coveralls upload failed"
